export { default as AboutPage } from './about'
export { default as ContactPage } from './contact'
export { default as DashboardPage } from './dashboard'
export { default as HomePage } from './home'
export { default as NotFoundPage } from './404'