export { default as AboutPage } from './about'
export { default as ContactPage } from './contact'
export { default as DashboardPage } from './dashboard'
export { default as HomePage } from './home'
export { default as NotFoundPage } from './404'
export { default as LoginPage } from '../auth/login'
export { default as SignupPage } from '../auth/signup'