export interface MenuItem {
  key: string;
  text: string;
  icon: string;
  path: string;
  roles: number[];
  items: MenuItem[];
}
export const navigation: MenuItem[] = [
  {
    key: "home",
    text: "Home",
    icon: "fa fa-home",
    path: "/statuses",
    roles: [1],
    items: [],
  },
  {
    key: "monthly-posting",
    text: "Monthly Posting",
    icon: "fa fa-calendar",
    path: "/my/monthly-posting",
    roles: [1],
    items: [],
  },
  {
    key: "savings",
    text: "Savings",
    icon: "fa fa-life-saver",
    path: "#",
    roles: [1],
    items: [
      {
        key: "post-savings",
        text: "Monthly Posting",
        icon: "",
        path: "/contact",
        roles: [1],
        items: [],
      },
      {
        key: "savings",
        text: "My Savings",
        icon: "",
        path: "/about",
        roles: [1],
        items: [],
      },
    ],
  },
  {
    key: "loan",
    text: "Loans",
    path: "#",
    icon: "fa fa-credit-card",
    roles: [1],
    items: [
      {
        key: "loan-application",
        text: "Loan Application",
        icon: "",
        path: "/home",
        roles: [1],
        items: [],
      },
      {
        key: "my-loans",
        text: "My loans",
        icon: "",
        path: "/contactt",
        roles: [1],
        items: [],
      },
    ],
  },
  {
    key: "messenger",
    text: "Shares",
    icon: "fa fa-money",
    path: "#",
    roles: [1],
    items: [
      {
        key: "post-shares",
        text: "Monthly Posting",
        icon: "",
        path: "/phones",
        roles: [1],
        items: [],
      },
      {
        key: "my-shares",
        text: "My Shares",
        icon: "",
        path: "/last-seen",
        roles: [1],
        items: [],
      },
    ],
  },
  {
    key: "dictionairies",
    text: "Dictionairies",
    icon: "fa fa-list",
    path: "#",
    roles: [2],
    items: [
      {
        key: "statuses",
        text: "Statuses",
        icon: "",
        path: "/admin/dictionairies/statuses",
        roles: [2],
        items: [],
      },
      {
        key: "transaction-types",
        text: "Transaction Types",
        icon: "",
        path: "/admin/dictionairies/transaction-types",
        roles: [2],
        items: [],
      },
      {
        key: "transaction-sources",
        text: "Transaction Sources",
        icon: "",
        path: "/admin/dictionairies/transaction-sources",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "onboarding",
    text: "Onboarding",
    icon: "fa fa-users",
    path: "#",
    roles: [2],
    items: [
      {
        key: "pending",
        text: "Pending",
        icon: "",
        path: "/admin/users/pending",
        roles: [2],
        items: [],
      },
      {
        key: "approved",
        text: "Approved",
        icon: "",
        path: "/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected",
        text: "Rejected",
        icon: "",
        path: "/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "savings",
    text: "Savings",
    icon: "fa fa-life-saver",
    path: "#",
    roles: [2],
    items: [
      {
        key: "pending",
        text: "Pending",
        icon: "",
        path: "/pendingf",
        roles: [2],
        items: [],
      },
      {
        key: "approved",
        text: "Approved",
        icon: "",
        path: "/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected",
        text: "Rejected",
        icon: "",
        path: "/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "loan",
    text: "Loans",
    path: "#",
    icon: "fa fa-credit-card",
    roles: [2],
    items: [
      {
        key: "pending",
        text: "Pending",
        icon: "",
        path: "/pendingf",
        roles: [2],
        items: [],
      },
      {
        key: "approved",
        text: "Approved",
        icon: "",
        path: "/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected",
        text: "Rejected",
        icon: "",
        path: "/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "messenger",
    text: "Shares",
    icon: "fa fa-money",
    path: "#",
    roles: [2],
    items: [
      {
        key: "pending",
        text: "Pending",
        icon: "",
        path: "/pendingf",
        roles: [2],
        items: [],
      },
      {
        key: "approved",
        text: "Approved",
        icon: "",
        path: "/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected",
        text: "Rejected",
        icon: "",
        path: "/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "penalty",
    text: "Penalties",
    icon: "fa fa-exclamation-circle",
    path: "#",
    roles: [2],
    items: [
      {
        key: "pending",
        text: "Pending",
        icon: "",
        path: "/pendingf",
        roles: [2],
        items: [],
      },
      {
        key: "approved",
        text: "Approved",
        icon: "",
        path: "/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected",
        text: "Rejected",
        icon: "",
        path: "/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
];
