export interface MenuItem {
  key: string;
  text: string;
  icon: string;
  path: string;
  roles: number[];
  items: MenuItem[];
}
export const navigation: MenuItem[] = [
  {
    key: "home",
    text: "Dashboard",
    icon: "fa fa-cubes",
    path: "/",
    roles: [1, 2],
    items: [],
  },
  {
    key: "my-monthly-postings",
    text: "Monthly Posting",
    icon: "fa fa-calendar",
    path: "",
    roles: [1],
    items: [
      {
        key: "my-monthly-posting-new",
        text: "New Monthly Posting",
        icon: "",
        path: "/my/monthly-posting/post",
        roles: [1],
        items: [],
      },
      {
        key: "my-monthly-posting-list",
        text: "My Monthly Postings",
        icon: "",
        path: "/my/monthly-posting/list",
        roles: [1],
        items: [],
      },
      {
        key: "my-monthly-posting-approve",
        text: "Guarantor Approvals",
        icon: "",
        path: "/my/monthly-posting/approvals",
        roles: [1],
        items: [],
      },
    ],
  },
  {
    key: "savings",
    text: "Savings",
    icon: "fa fa-life-saver",
    path: "#",
    roles: [1],
    items: [
      {
        key: "my-savings",
        text: "My Savings",
        icon: "",
        path: "/my/savings/list",
        roles: [1],
        items: [],
      },
      {
        key: "my-social-funds",
        text: "My Social Funds",
        icon: "",
        path: "/my/social-funds/list",
        roles: [1],
        items: [],
      },
    ],
  },
  {
    key: "loan",
    text: "Loans",
    path: "#",
    icon: "fa fa-credit-card",
    roles: [1],
    items: [
      {
        key: "my-loans",
        text: "My Loans",
        icon: "",
        path: "/my/loans/list",
        roles: [1],
        items: [],
      },
    ],
  },
  {
    key: "shares",
    text: "Shares",
    icon: "fa fa-money",
    path: "#",
    roles: [1],
    items: [
      {
        key: "my-shares",
        text: "My Shares",
        icon: "",
        path: "/my/shares/list",
        roles: [1],
        items: [],
      },
    ],
  },
  {
    key: "messenger",
    text: "Penalties",
    icon: "fa fa-money",
    path: "#",
    roles: [1],
    items: [
      {
        key: "my-penalties",
        text: "My Penalties",
        icon: "",
        path: "/my/penalties/list",
        roles: [1],
        items: [],
      },
    ],
  },
  {
    key: "user-member-query",
    text: "Member Queries",
    icon: "fa fa-question-circle",
    path: "#",
    roles: [1],
    items: [
      {
        key: "user-member-query-list",
        text: "My Queries",
        icon: "",
        path: "/my/member-queries/list",
        roles: [1],
        items: [],
      },
      {
        key: "user-member-query-add",
        text: "Submit Query",
        icon: "",
        path: "/my/member-queries/submit",
        roles: [1],
        items: [],
      },
    ],
  },
   {
    key: "guarantors",
    text: "Guarantors",
    icon: "fa fa-money",
    path: "#",
    roles: [1],
    items: [
      {
        key: "my-penalties",
        text: "My Guarantors",
        icon: "",
        path: "/my/guarantors/list",
        roles: [1],
        items: [],
      },
    ],
  },
     {
    key: "pay-methods",
    text: "Payment Methods",
    icon: "fa fa-money",
    path: "#",
    roles: [1],
    items: [
      {
        key: "my-penalties",
        text: "My Payment Methods",
        icon: "",
        path: "/my/payment-methods/list",
        roles: [1],
        items: [],
      },
    ],
  },
  {
    key: "app-reports",
    text: "Reports",
    icon: "fa fa-bar-chart-o",
    path: "#",
    roles: [1, 2],
    items: [
      {
        key: "member-summary",
        text: "Member Summary",
        icon: "",
        path: "/reports/member-summary",
        roles: [1, 2],
        items: [],
      },
      {
        key: "monthly-summary",
        text: "Monthly Summary",
        icon: "",
        path: "/reports/monthly-summary",
        roles: [1, 2],
        items: [],
      },
      {
        key: "interest-sharing",
        text: "Interest Sharing",
        icon: "",
        path: "/reports/interest-sharing",
        roles: [1, 2],
        items: [],
      },
      {
        key: "time-value",
        text: "Time value",
        icon: "",
        path: "/reports/time-value-summary",
        roles: [1, 2],
        items: [],
      },
      {
        key: "expense-earning-summary",
        text: "Expense Earnings",
        icon: "",
        path: "/reports/expense-earnings-summary",
        roles: [1, 2],
        items: [],
      },
    ],
  },
    {
    key: "users",
    text: "Users",
    icon: "fa fa-bell",
    path: "#",
    roles: [2],
    items: [
      {
        key: "all-users",
        text: "All Users",
        icon: "",
        path: "/admin/users/list",
        roles: [2],
        items: [],
      },
      {
        key: "pending",
        text: "Pending",
        icon: "",
        path: "/pendingf",
        roles: [2],
        items: [],
      },
      {
        key: "approved",
        text: "Approved",
        icon: "",
        path: "/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected",
        text: "Rejected",
        icon: "",
        path: "/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "dictionairies",
    text: "Dictionairies",
    icon: "fa fa-cube",
    path: "#",
    roles: [2],
    items: [
      {
        key: "statuses",
        text: "Statuses",
        icon: "",
        path: "/admin/dictionairies/statuses",
        roles: [2],
        items: [],
      },
      {
        key: "transaction-types",
        text: "Transaction Types",
        icon: "",
        path: "/admin/dictionairies/transaction-types",
        roles: [2],
        items: [],
      },
      {
        key: "transaction-sources",
        text: "Sources",
        icon: "",
        path: "/admin/dictionairies/transaction-sources",
        roles: [2],
        items: [],
      },
      {
        key: "attendance-types",
        text: "Attendance Types",
        icon: "",
        path: "/admin/dictionairies/attendance-types",
        roles: [2],
        items: [],
      },
      {
        key: "review-stages",
        text: "Review Stages",
        icon: "",
        path: "/admin/dictionairies/review-stages",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "onboarding",
    text: "Onboarding",
    icon: "fa fa-users",
    path: "#",
    roles: [2],
    items: [
      {
        key: "admin-members-list",
        text: "All Members",
        icon: "",
        path: "/admin/members/list",
        roles: [2],
        items: [],
      },
      {
        key: "admin-members-submitted",
        text: "Submitted",
        icon: "",
        path: "/admin/members/submitted",
        roles: [2],
        items: [],
      },
      {
        key: "admin-members-approved",
        text: "Approved",
        icon: "",
        path: "/admin/members/approved",
        roles: [2],
        items: [],
      },
      {
        key: "admin-members-rejected",
        text: "Rejected",
        icon: "",
        path: "/admin/members/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "posting-periods",
    text: "Posting Periods",
    icon: "fa fa-calendar",
    path: "#",
    roles: [2],
    items: [
      {
        key: "all-periods",
        text: "All Posting Periods",
        icon: "",
        path: "/admin/posting-periods/list",
        roles: [2],
        items: [],
      },
      {
        key: "submitted-periods",
        text: "Submitted",
        icon: "",
        path: "/admin/posting-periods/submitted",
        roles: [2],
        items: [],
      },
      {
        key: "approved-periods",
        text: "Approved",
        icon: "",
        path: "/admin/posting-periods/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected-periods",
        text: "Rejected",
        icon: "",
        path: "/admin/posting-periods/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "admin-monthly-posting",
    text: "Monthly Postings",
    icon: "fa fa-bar-chart",
    path: "#",
    roles: [2],
    items: [
      {
        key: "admin-monthly-posting-list",
        text: "All Monthly Postings",
        icon: "",
        path: "/admin/monthly-postings/list",
        roles: [2],
        items: [],
      },
      {
        key: "admin-monthly-posting-submitted",
        text: "Submitted",
        icon: "",
        path: "/admin/monthly-postings/submitted",
        roles: [2],
        items: [],
      },
      {
        key: "admin-monthly-posting-approved",
        text: "Approved",
        icon: "",
        path: "/admin/monthly-postings/approved",
        roles: [2],
        items: [],
      },
      {
        key: "admin-monthly-posting-rejceted",
        text: "Rejected",
        icon: "",
        path: "/admin/monthly-postings/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "expense-earnings",
    text: "Expense & Earnings",
    icon: "fa fa-exchange",
    path: "#",
    roles: [2],
    items: [
      {
        key: "groups",
        text: "All Groups",
        icon: "",
        path: "/admin/expense-earning/group/list",
        roles: [2],
        items: [],
      },
      {
        key: "all-expense-earnings",
        text: "All Expense & Earning",
        icon: "",
        path: "/admin/expenses-earnings/list",
        roles: [2],
        items: [],
      },
      {
        key: "submitted-expense-earnings",
        text: "Submitted",
        icon: "",
        path: "/admin/expenses-earnings/submitted",
        roles: [2],
        items: [],
      },
      {
        key: "approved-expense-earnings",
        text: "Approved",
        icon: "",
        path: "/admin/expenses-earnings/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected-expense-earnings",
        text: "Rejected",
        icon: "",
        path: "/admin/expenses-earnings/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "savings",
    text: "Savings",
    icon: "fa fa-life-saver",
    path: "#",
    roles: [2],
    items: [
      {
        key: "pending",
        text: "Pending",
        icon: "",
        path: "/pendingf",
        roles: [2],
        items: [],
      },
      {
        key: "approved",
        text: "Approved",
        icon: "",
        path: "/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected",
        text: "Rejected",
        icon: "",
        path: "/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "loan",
    text: "Loans",
    path: "#",
    icon: "fa fa-credit-card",
    roles: [2],
    items: [
      {
        key: "pending",
        text: "Pending",
        icon: "",
        path: "/pendingf",
        roles: [2],
        items: [],
      },
      {
        key: "approved",
        text: "Approved",
        icon: "",
        path: "/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected",
        text: "Rejected",
        icon: "",
        path: "/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "messenger",
    text: "Shares",
    icon: "fa fa-money",
    path: "#",
    roles: [2],
    items: [
      {
        key: "pending",
        text: "Pending",
        icon: "",
        path: "/pendingf",
        roles: [2],
        items: [],
      },
      {
        key: "approved",
        text: "Approved",
        icon: "",
        path: "/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected",
        text: "Rejected",
        icon: "",
        path: "/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "penalty",
    text: "Penalties",
    icon: "fa fa-exclamation-circle",
    path: "#",
    roles: [2],
    items: [
      {
        key: "pending",
        text: "Pending",
        icon: "",
        path: "/pendingf",
        roles: [2],
        items: [],
      },
      {
        key: "approved",
        text: "Approved",
        icon: "",
        path: "/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected",
        text: "Rejected",
        icon: "",
        path: "/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "announcements",
    text: "Announcements",
    icon: "fa fa-bell",
    path: "#",
    roles: [2],
    items: [
      {
        key: "all-announcements",
        text: "All Announcements",
        icon: "",
        path: "/admin/announcements/list",
        roles: [2],
        items: [],
      },
      {
        key: "pending",
        text: "Pending",
        icon: "",
        path: "/pendingf",
        roles: [2],
        items: [],
      },
      {
        key: "approved",
        text: "Approved",
        icon: "",
        path: "/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected",
        text: "Rejected",
        icon: "",
        path: "/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "meetings",
    text: "Meetings",
    icon: "fa fa-suitcase",
    path: "#",
    roles: [2],
    items: [
      {
        key: "all-meetings",
        text: "All Meetings",
        icon: "",
        path: "/admin/meetings/list",
        roles: [2],
        items: [],
      },
      {
        key: "pending",
        text: "Pending",
        icon: "",
        path: "/pendingf",
        roles: [2],
        items: [],
      },
      {
        key: "approved",
        text: "Approved",
        icon: "",
        path: "/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected",
        text: "Rejected",
        icon: "",
        path: "/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "member-query",
    text: "Member Queries",
    icon: "fa fa-question-circle",
    path: "#",
    roles: [2],
    items: [
      {
        key: "member-query-list",
        text: "All Member Queries",
        icon: "",
        path: "/admin/member-queries/list",
        roles: [2],
        items: [],
      },
      {
        key: "pending",
        text: "Pending",
        icon: "",
        path: "/pendingf",
        roles: [2],
        items: [],
      },
      {
        key: "approved",
        text: "Approved",
        icon: "",
        path: "/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected",
        text: "Rejected",
        icon: "",
        path: "/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
    {
    key: "admin-payment-methods",
    text: "Payment Methods",
    icon: "fa fa-question-circle",
    path: "#",
    roles: [2],
    items: [
      {
        key: "admin-payment-method-list",
        text: "All Payment Methods",
        icon: "",
        path: "/admin/payment-methods/list",
        roles: [2],
        items: [],
      },
      {
        key: "pending",
        text: "Pending",
        icon: "",
        path: "/pendingf",
        roles: [2],
        items: [],
      },
      {
        key: "approved",
        text: "Approved",
        icon: "",
        path: "/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected",
        text: "Rejected",
        icon: "",
        path: "/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
      {
    key: "admin-guarantors",
    text: "Guarantors",
    icon: "fa fa-question-circle",
    path: "#",
    roles: [2],
    items: [
      {
        key: "admin-guarantor-list",
        text: "All Guarantors",
        icon: "",
        path: "/admin/guarantors/list",
        roles: [2],
        items: [],
      },
      {
        key: "pending",
        text: "Pending",
        icon: "",
        path: "/pendingf",
        roles: [2],
        items: [],
      },
      {
        key: "approved",
        text: "Approved",
        icon: "",
        path: "/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected",
        text: "Rejected",
        icon: "",
        path: "/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "knowledge-base",
    text: "Knowledge Base",
    icon: "fa fa-book",
    path: "#",
    roles: [2],
    items: [
      {
        key: "categories",
        text: "All Categories",
        icon: "",
        path: "/admin/knowledge-base/category/list",
        roles: [2],
        items: [],
      },
      {
        key: "articles",
        text: "All Articles",
        icon: "",
        path: "/admin/knowledge-base/article/list",
        roles: [2],
        items: [],
      },
      {
        key: "pending",
        text: "Pending",
        icon: "",
        path: "/pendingf",
        roles: [2],
        items: [],
      },
      {
        key: "approved",
        text: "Approved",
        icon: "",
        path: "/approved",
        roles: [2],
        items: [],
      },
      {
        key: "rejected",
        text: "Rejected",
        icon: "",
        path: "/rejected",
        roles: [2],
        items: [],
      },
    ],
  },
  {
    key: "configuration",
    text: "Configuration",
    icon: "fa fa-gears ",
    path: "#",
    roles: [2],
    items: [
      {
        key: "sacco",
        text: "SACCO",
        icon: "",
        path: "/admin/config/sacco",
        roles: [2],
        items: [],
      },
      {
        key: "application",
        text: "Application",
        icon: "",
        path: "/approved",
        roles: [2],
        items: [],
      },
    ],
  },
];
